# Generated by Django 4.0 on 2022-03-21 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0011_alter_userdetails_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.workerdetails')),
            ],
        ),
    ]
