# Generated by Django 4.0 on 2022-03-24 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_userdetails_profilepic'),
        ('emplapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.login'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Display_images/'),
        ),
    ]
