# Generated by Django 4.0 on 2022-03-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_login_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='login',
            new_name='userlogin',
        ),
    ]
