# Generated by Django 4.0 on 2022-03-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20220311_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='User_images/'),
        ),
        migrations.AlterField(
            model_name='workerdetails',
            name='w_profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='Worker_images/'),
        ),
    ]
