# Generated by Django 4.0 on 2022-03-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_userdetails_profilepic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profilePic',
            field=models.ImageField(default='', upload_to='User_images/'),
        ),
    ]
