# Generated by Django 4.0 on 2022-03-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_userdetails_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='User_images/'),
        ),
    ]
