# Generated by Django 4.0 on 2022-03-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_userdetails_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='mode',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
