# Generated by Django 4.0 on 2022-04-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_alter_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profilePic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='User_images/'),
        ),
    ]
