# Generated by Django 4.0 on 2022-04-09 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='login',
            new_name='login_user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='star',
        ),
        migrations.AddField(
            model_name='review',
            name='worker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='userapp.workerdetails'),
            preserve_default=False,
        ),
    ]
